### PR TITLE
Update ReadMe

### PR DESCRIPTION
**Pull request by InsightCracker**
Add Technologies used to the ReadMe, Link to the Contribution guideline and correct sentence case mistake

### CODE REVIEW

**Comment by ch3ber** [comment]
The readme needs a .png/.svg icon in the technologies section.

```
Typescript [icon]
Docusaurus [icon]
```

Add the icons in the route `static/img/icons`

**Review by ch3ber — CHANGES_REQUESTED** [review]
Add icons

**Comment by InsightCracker** [comment]
Ok

**Comment by InsightCracker** [comment]
I've added the icon can you please merge it

**Pull request closed without merging**
